### PR TITLE
Implemented Dungeon Builder Algorithm

### PR DESCRIPTION
**Pull request by josephlatina**
### Features

- Added Game Manager script which handles different game states (currently only have `gameStarted` implemented). This is also where the call to generate the dungeon is made
- Created the DungeonBuilder script that handles the algorithm and logic for instantiating the dungeon
- Created a scriptable object for the first dungeon level where it takes in:
   - list of room node graphs (to choose one out of for the level). Currently I only have one graph.
   - list of room templates to choose out of (should have one for each room node type in the room node graphs)
- _Small change_: I had set the sorting layer for the player and items to be on the `Instances` layer such that it will show in front of the dungeon room layer

### Testing

- I had configured the `R` key such that when it is pressed anytime within the game session, the dungeon builder algorithm will get triggered and the dungeon gets regenerated in a different layout (but still adhering to the relationships dictated in the selected room node graph - that's why even if there is only one room node graph, the layout changes everytime). **Note that this key is only for testing purposes and will be removed when the game is finalized.**

### Demo

https://github.com/josephlatina/DungeonCrawler/assets/74115441/171e4371-b246-4618-95af-8f60c014775b

### CODE REVIEW

**Comment by jaizon2000** [comment]
The dungeon generation doesn't seem to work for me when I play the game.

Unity_xGPqWvNFZX

**Comment by josephlatina** [comment]
I must have not saved the scene where I added the game manager object. I pushed a commit, try now if it works on your end @jaizon2000

**Comment by jaizon2000** [comment]
works as expected
There's something I noticed while testing:
Sometimes walking on wall after generating a new dungeon, player appears above the wall tile. The player doesn't go over the wall. Collisions are working fine. The only problem is the player appearing on top of the tile.
image

There are times when it's working fine like this, though
image


Actions taken:
1. Press R
2. Walk around walls until I find one where the player appears on top of the tile

**Review by jaizon2000 — DISMISSED** [review]
Apart from this issue https://github.com/josephlatina/DungeonCrawler/pull/15#issuecomment-1937410624 everything work as written in the description.

**Comment by josephlatina** [comment]
Good catch, I've corrected the sorting layer of the walls for the corridors (they were initially in front of the layer the player is sitting on) @jaizon2000

**Review by jaizon2000 — APPROVED** [review]
> Good catch, I've corrected the sorting layer of the walls for the corridors (they were initially in front of the layer the player is sitting on) @jaizon2000

Problem is fixed!

**Pull request merged**
