### PR TITLE
Level Progression and Pause Functionality

### PR DESCRIPTION
**Pull request by josephlatina**
### Features

- Added Level 2 templates and scriptable object for level continuation
- Added Level Progression mechanic: 
   - game states have been added and implemented for `Level Completed`, `Game Won`, `Game Lost`, `Game Paused`.
   - there is a fade screen UI transition with text when entering new levels and if game has been won or lost (game lost will have to be tested after health+damage functionality has been implemented)
- Pause functionality and UI has been implemented: player can unpause or quit and go back to main menu
- Small change: added game music on main menu

### Testing
- Load the 'Home' scene and play the game. You should be starting from the Main Menu. From there, click `Start` to play.
- To surface the pause menu, simply press the `Esc` button. From there you can unpause game or go back to main menu
- Reach the 'Exit Room' in Level 1 in order to get to the next level
- Reach the 'Exit Room' in Level 2 in order to clear the game and head back to main menu

### Demo
- Starting from Main Menu

https://github.com/josephlatina/DungeonCrawler/assets/74115441/e539718d-3815-45af-ae74-4f73702771ed

- Triggering Pause Menu

https://github.com/josephlatina/DungeonCrawler/assets/74115441/6c867d20-a14a-4285-804d-fe8dc8049d4a

- Level Completed

https://github.com/josephlatina/DungeonCrawler/assets/74115441/54d1e2d8-f1a5-4dac-9c43-2024607b3583

- Game Won

https://github.com/josephlatina/DungeonCrawler/assets/74115441/6b6e583c-eb22-475c-b3de-a78cec1ae4df

### CODE REVIEW

**Comment by jaizon2000** [comment]
I really like the GUI you have for the pause menu. Was wondering if you can change the button on the home page to what you have on the pause menu.
image

**Review by jaizon2000 — APPROVED** [review]
looks good and i made those UI changes to button

**Comment by josephlatina** [comment]
[MS3-4: Level Progression](https://trello.com/c/SDS7jPee/33-ms3-4-level-progression)

**Comment by josephlatina** [comment]
[MS3-4: Pause Functionality](https://trello.com/c/MVb98R0R/76-ms3-4-pause-functionality)

**Pull request merged**
