### PR TITLE
Player controls

### PR DESCRIPTION
**Pull request by joshualeecoss**
The player now has functioning controls!

- WASD (or arrow keys) to move
- SPACE to roll
- Left Mouse Button to melee attack
- Right Mouse Button to range attack
- F to heal
- E to interact

I made the decision not to add Pause function at this point, as I feel it's more game state logic than player logic. We've also decided that the map screen is not going to be implemented in the MVP so I have not added that functionality as well.

To test the controls (Either from the main scene or the PlayerControlsTestScene):
- Move the character with WASD (or arrow keys)
- Press SPACE when moving (character will not roll when standing still). Character should turn red and move quickly in moving direction for a short time.
- Press the left mouse button while moving or standing still to enter the Melee State. The MeleeColider under the player in the hierarchy should enable while in the state and disable when exiting the state. Character will flash blue to show that it is in the Melee State.
- Press the right mouse button while moving or standing still to enter the Ranged State. You should see a yellow line drawn from the character to the mouse. Character will flash yellow.
- Press F to enter Heal State while moving or standing still. Character will flash green and a console message should pop up telling you when the character starts and stops healing.
- Move the character close to one of the interaction test objects. Pressing E near them should change their colour and show a console message. Obviously will still need to be hooked up to any interactable systems. (Highlighting the InteractTrigger under the player in the hierarchy will help to visualize how close you have to be to interact).
image

None of the states should be able to overlap with each other (ie you can't roll and attack at the same time), although movement is still possible when attacking/healing.

Let me know if there are any questions or if anything is unclear!

### CODE REVIEW

**Review by josephlatina — COMMENTED** [review]
Very cool!

Tested all functionalities and it looks good! I do have a question about the ranged attack because I know you mentioned that there should be a line drawn from the player to where the mouse cursor is at but I don't see any line (though the player is flashing yellow)


https://github.com/josephlatina/DungeonCrawler/assets/74115441/e87c9952-7a7d-4551-ad49-f8d3a9977766

Update: I see it now after turning on gizmos!


https://github.com/josephlatina/DungeonCrawler/assets/74115441/52aab1c2-503f-47fd-8146-927fbb318965

**Comment by joshualeecoss** [comment]
Forgot to mention that gizmos need to be turned on in your game view to see the ranged attack line!

**Comment by joshualeecoss** [comment]
> Very cool!
> 
> Tested all functionalities and it looks good! I do have a question about the ranged attack because I know you mentioned that there should be a line drawn from the player to where the mouse cursor is at but I don't see any line (though the player is flashing yellow)
> 
>  Screen.Recording.2024-01-29.at.2.39.57.PM.mov

Forgot to mention that gizmos need to be turned on in your game view to see the ranged attack line!

**Review by josephlatina — APPROVED** [review]
Looks good to me! All functionalities have been tested

**Comment by joshualeecoss** [comment]
[MS2-2: Player Controls](https://trello.com/c/mhy7g9wc/37-ms2-2-player-controls)

**Pull request merged**
